name: "Exercicio 2"

on:
  push:
  
jobs:
  cria_e_upload_artefato:
    name: "Cria Artefato e faz upload"
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout 
        uses: actions/checkout@v3.3.0


      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: repositorio_do_Alexandre
          # A file, directory or wildcard pattern that describes what to upload
          path: .
   
          retention-days: 15
